# Navigation Links du Laboratoire DISP
main:
  - name: Le Laboratoire
    url: /labo/
    weight: 10

  # 1. On crée l'onglet "Chapeau" (sans URL ou pointant vers la page liste)
  # On lui donne un ID unique appelé "axes_root"
  - id: axes_root
    name: Axes scientifiques
    url: /axes/
    weight: 20

  # 2. On attache le premier sous-menu en définissant son parent
  - name: Axe Gestion et Optimisation des Opérations
    url: /axes/axe-g2o/
    parent: Axes scientifiques
    weight: 21

  # 3. On attache le deuxième sous-menu au même parent
  - name: Axe Systèmes d'Information et Données
    url: /axes/axe-sido/
    parent: Axes scientifiques
    weight: 22
  
  # 4. On attache le troisième sous-menu au même parent
  - name: Axe TOOLS
    url: /axes/axe-tools/
    parent: Axes scientifiques
    weight: 23

  - name: Membres
    url: /membres/
    weight: 30
  - name: Projets
    url: /project/
    weight: 40
  - name: Thèses
    url: /thesis/
    weight: 50
  - name: Publications
    url: /publication/
    weight: 60